---
#
# SPDX-License-Identifier: GPL-3.0-or-later

stages:
  - check
  - build

check:
  before_script:
    # NOTE: Install latest archlinux-keyring before upgrading system. In the
    # future this should not be needed anymore when we can guarantee a valid
    # keyring for longer:
    # https://gitlab.archlinux.org/archlinux/archlinux-keyring/-/issues/4
    - pacman -Sy --needed --noconfirm archlinux-keyring
    - pacman --noconfirm -Syu --needed make shellcheck
  script:
    - make check
  stage: check
  interruptible: true

.build:
  before_script:
    - pacman -Sy --needed --noconfirm archlinux-keyring
    - pacman -Syu --needed --noconfirm arch-install-scripts bash dosfstools e2fsprogs erofs-utils gnupg grub jq libarchive libisoburn mtools openssl qemu-headless squashfs-tools zsync
  script:
    - ./.gitlab/ci/build_syncopated.sh
  stage: build
  tags:
    - vm

build_short:
  extends: .build
  only:
    refs:
      - master
      - merge_requests
    changes:
      - airootfs/**/*
      - efiboot/**/*
      - grub/*
      - syslinux/*
      - configs/**/*
      - packages.x86_64
      - pacman.conf
      - profiledef.sh
      - .gitlab-ci.yml
      - .gitlab/ci/*
  interruptible: true
